// Product catalog for The College Closet.
// Keep product data structured so filters, inquiry links, and validation checks do not parse display copy.
window.collegeClosetProducts = [
    {
        "id": "fsu-fsu-crewneck-pullover",
        "name": "FSU Crewneck Pullover",
        "school": "FSU",
        "schoolDisplayName": "Florida State",
        "category": "crewneck",
        "size": "M",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 70,
        "resalePrice": 30,
        "image": "fsu pullover.jpeg",
        "status": "available"
    },
    {
        "id": "maryland-maryland-terrapins-under-armour-script-pullover",
        "name": "Maryland Terrapins Under Armour Script Pullover",
        "school": "Maryland",
        "schoolDisplayName": "Maryland",
        "category": "pullover",
        "size": "S",
        "condition": "Like New",
        "brand": "Under Armour",
        "originalPrice": 75,
        "resalePrice": 30,
        "image": "maryland pullover.webp",
        "status": "available"
    },
    {
        "id": "purdue-purdue-university-arch-logo-black-tee",
        "name": "Purdue University Arch Logo Black Tee",
        "school": "Purdue",
        "schoolDisplayName": "Purdue",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 40,
        "resalePrice": 15,
        "image": "black purdue tee.jpeg",
        "status": "available"
    },
    {
        "id": "purdue-purdue-university-arch-logo-gray-tee",
        "name": "Purdue University Arch Logo Gray Tee",
        "school": "Purdue",
        "schoolDisplayName": "Purdue",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 40,
        "resalePrice": 15,
        "image": "purdue grey shirt.jpg",
        "status": "available"
    },
    {
        "id": "purdue-purdue-university-purdue-pete-tee",
        "name": "Purdue University Purdue Pete Tee",
        "school": "Purdue",
        "schoolDisplayName": "Purdue",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 40,
        "resalePrice": 15,
        "image": "product-images/purdue-pete-tee.jpg",
        "status": "available"
    },
    {
        "id": "penn-state-penn-state-nittany-lions-v-cut-hoodie",
        "name": "Penn State Nittany Lions 'V Cut' Hoodie",
        "school": "Penn State",
        "schoolDisplayName": "Penn State",
        "category": "hoodie",
        "size": "M",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 65,
        "resalePrice": 25,
        "image": "penn state navy hoodie.png",
        "status": "available"
    },
    {
        "id": "minnesota-university-of-minnesota-nike-swoosh-tee",
        "name": "University of Minnesota Nike Swoosh Tee",
        "school": "Minnesota",
        "schoolDisplayName": "University of Minnesota",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "Nike",
        "originalPrice": 45,
        "resalePrice": 15,
        "image": "product-images/minnesota-grey-tee.jpg",
        "status": "available"
    },
    {
        "id": "unc-north-carolina-tar-heels-champion-tee",
        "name": "North Carolina Tar Heels Champion Tee",
        "school": "UNC",
        "schoolDisplayName": "North Carolina",
        "category": "tee",
        "size": "S",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 35,
        "resalePrice": 15,
        "image": "UNC shirt.jpg",
        "status": "available"
    },
    {
        "id": "wisconsin-wisconsin-badgers-colosseum-hoodie-cutoff",
        "name": "Wisconsin Badgers Colosseum Hoodie Cutoff",
        "school": "Wisconsin",
        "schoolDisplayName": "University of Wisconsin",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "Colosseum",
        "originalPrice": 30,
        "resalePrice": 15,
        "image": "wisco cutoff.avif",
        "status": "available"
    },
    {
        "id": "penn-state-penn-state-3-stripes-pullover",
        "name": "Penn State 3 Stripes Pullover",
        "school": "Penn State",
        "schoolDisplayName": "Penn State",
        "category": "pullover",
        "size": "M",
        "condition": "Like New",
        "brand": "Adidas",
        "originalPrice": 65,
        "resalePrice": 30,
        "image": "psu hoodie.jpeg",
        "status": "available"
    },
    {
        "id": "wisconsin-wisconsin-badgers-tie-dye-tee",
        "name": "Wisconsin Badgers Tie-Dye Tee",
        "school": "Wisconsin",
        "schoolDisplayName": "University of Wisconsin",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 35,
        "resalePrice": 15,
        "image": "product-images/wisconsin-tie-dye-tee.jpg",
        "status": "available"
    },
    {
        "id": "wisconsin-wisconsin-golf-hat",
        "name": "Wisconsin Golf Hat",
        "school": "Wisconsin",
        "schoolDisplayName": "University of Wisconsin",
        "category": "hat",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 35,
        "resalePrice": 15,
        "image": "wisconsin hat.png",
        "status": "available"
    },
    {
        "id": "minnesota-university-of-minnesota-cutoff-tee",
        "name": "University of Minnesota Cutoff Tee",
        "school": "Minnesota",
        "schoolDisplayName": "University of Minnesota",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 35,
        "resalePrice": 15,
        "image": "minnesota grey cutoff.png",
        "status": "available"
    },
    {
        "id": "yale-yale-youth-global-studies-2024-tee",
        "name": "Yale Youth Global Studies 2024 Tee",
        "school": "Yale",
        "schoolDisplayName": "Yale",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 25,
        "resalePrice": 5,
        "image": "yale ygs navy shirt.png",
        "status": "available"
    },
    {
        "id": "chicago-university-of-chicago-crewneck",
        "name": "University of Chicago Crewneck",
        "school": "Chicago",
        "schoolDisplayName": "University of Chicago",
        "category": "crewneck",
        "size": "S",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 65,
        "resalePrice": 25,
        "image": "product-images/uchicago-maroon-crewneck.jpg",
        "status": "available"
    },
    {
        "id": "stanford-stanford-university-basketball-tee",
        "name": "Stanford University Basketball Tee",
        "school": "Stanford",
        "schoolDisplayName": "Stanford",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 35,
        "resalePrice": 10,
        "image": "stanford tee.jpeg",
        "status": "available"
    },
    {
        "id": "yale-yale-bulldogs-champion-crewneck",
        "name": "Yale Bulldogs Champion Crewneck",
        "school": "Yale",
        "schoolDisplayName": "Yale",
        "category": "crewneck",
        "size": "M",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 55,
        "resalePrice": 25,
        "image": "yalepullvoer.avif",
        "status": "available"
    },
    {
        "id": "auburn-auburn-tigers-colosseum-athletic-tee",
        "name": "Auburn Tigers Colosseum Athletic Tee",
        "school": "Auburn",
        "schoolDisplayName": "Auburn",
        "category": "tee",
        "size": "M",
        "condition": "Like New",
        "brand": "Colosseum",
        "originalPrice": 35,
        "resalePrice": 15,
        "image": "auburnshirt.jpg",
        "status": "available"
    },
    {
        "id": "purdue-purdue-university-open-bottom-sweatpants",
        "name": "Purdue University Open Bottom Sweatpants",
        "school": "Purdue",
        "schoolDisplayName": "Purdue",
        "category": "sweatpants",
        "size": "M",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 60,
        "resalePrice": 23,
        "image": "purduesweats.jpeg",
        "status": "available"
    },
    {
        "id": "syracuse-colosseum-syracuse-orange-hoodie",
        "name": "Colosseum Syracuse Orange Hoodie",
        "school": "Syracuse",
        "schoolDisplayName": "Syracuse",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "Colosseum",
        "originalPrice": 70,
        "resalePrice": 35,
        "image": "syracusehoodie.jpg",
        "status": "available"
    },
    {
        "id": "colorado-colorado-boulder-buffaloes-arch-logo-hoodie",
        "name": "Colorado Boulder Buffaloes Arch Logo Hoodie",
        "school": "Colorado",
        "schoolDisplayName": "University of Colorado Boulder",
        "category": "hoodie",
        "size": "S",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 70,
        "resalePrice": 35,
        "image": "boulderhoodie.avif",
        "status": "available"
    },
    {
        "id": "umass-massachusetts-amherst-fleece-hoodie",
        "name": "Massachusetts Amherst Fleece Hoodie",
        "school": "UMass",
        "schoolDisplayName": "University of Massachusetts Amherst",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 65,
        "resalePrice": 40,
        "image": "umass.jpeg",
        "status": "available"
    },
    {
        "id": "bucknell-bucknell-university-orange-arch-tee",
        "name": "Bucknell University Orange Arch Tee",
        "school": "Bucknell",
        "schoolDisplayName": "Bucknell",
        "category": "tee",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 35,
        "resalePrice": 20,
        "image": "bucknelldarktee.jpg",
        "status": "available"
    },
    {
        "id": "bucknell-bucknell-university-yellow-arch-long-sleeve",
        "name": "Bucknell University Yellow Arch Long Sleeve",
        "school": "Bucknell",
        "schoolDisplayName": "Bucknell",
        "category": "long-sleeve",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 40,
        "resalePrice": 25,
        "image": "buckyells.png",
        "status": "available"
    },
    {
        "id": "bucknell-bucknell-university-orange-arch-long-sleeve",
        "name": "Bucknell University Orange Arch Long Sleeve",
        "school": "Bucknell",
        "schoolDisplayName": "Bucknell",
        "category": "long-sleeve",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 40,
        "resalePrice": 25,
        "image": "buckorgls.png",
        "status": "available"
    },
    {
        "id": "bucknell-bucknell-university-navy-arch-hoodie",
        "name": "Bucknell University Navy Arch Hoodie",
        "school": "Bucknell",
        "schoolDisplayName": "Bucknell",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 65,
        "resalePrice": 35,
        "image": "bucknellhoodie.png",
        "status": "available"
    },
    {
        "id": "georgetown-champion-georgetown-grey-arch-hoodie",
        "name": "Champion Georgetown Grey Arch Hoodie",
        "school": "Georgetown",
        "schoolDisplayName": "Georgetown",
        "category": "hoodie",
        "size": "XL",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 70,
        "resalePrice": 40,
        "image": "gtownhoodie.png",
        "status": "available"
    },
    {
        "id": "bc-boston-college-eagles-new-balance-fleece-hoodie",
        "name": "Boston College Eagles New Balance Fleece Hoodie",
        "school": "BC",
        "schoolDisplayName": "Boston College",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "New Balance",
        "originalPrice": 70,
        "resalePrice": 40,
        "image": "bchoodie.png",
        "status": "available"
    },
    {
        "id": "bu-boston-university-terriers-champion-hoodie",
        "name": "Boston University Terriers Champion Hoodie",
        "school": "BU",
        "schoolDisplayName": "Boston University",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 70,
        "resalePrice": 40,
        "image": "buhoodie.jpg",
        "status": "available"
    },
    {
        "id": "miamio-miami-university-ohio-hoodie",
        "name": "Miami University (Ohio) Hoodie",
        "school": "MiamiO",
        "schoolDisplayName": "Miami University (Ohio)",
        "category": "hoodie",
        "size": "M",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 60,
        "resalePrice": 30,
        "image": "miamihoodie.png",
        "status": "available"
    },
    {
        "id": "michigan-michigan-wolverines-champion-hoodie",
        "name": "Michigan Wolverines Champion Hoodie",
        "school": "Michigan",
        "schoolDisplayName": "University of Michigan",
        "category": "hoodie",
        "size": "S",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 60,
        "resalePrice": 30,
        "image": "product-images/michigan-navy-hoodie.jpg",
        "status": "available"
    },
    {
        "id": "michigan-michigan-wolverines-lululemon-tee",
        "name": "Michigan Wolverines Lululemon Tee",
        "school": "Michigan",
        "schoolDisplayName": "University of Michigan",
        "category": "tee",
        "size": "S",
        "condition": "Like New",
        "brand": "Lululemon",
        "originalPrice": 45,
        "resalePrice": 20,
        "image": "michlulu.png",
        "status": "available"
    },
    {
        "id": "villa-villanova-wildcats-nike-basketball-family-long-sleeve-tee",
        "name": "Villanova Wildcats Nike Basketball Family Long Sleeve Tee",
        "school": "Villa",
        "schoolDisplayName": "Villanova",
        "category": "long-sleeve",
        "size": "M",
        "condition": "Brand New",
        "brand": "Nike",
        "originalPrice": 45,
        "resalePrice": 25,
        "image": "villafamily.avif",
        "status": "available"
    },
    {
        "id": "villa-villanova-wildcats-logo-tee",
        "name": "Villanova Wildcats Logo Tee",
        "school": "Villa",
        "schoolDisplayName": "Villanova",
        "category": "tee",
        "size": "M",
        "condition": "Brand New",
        "brand": "College apparel",
        "originalPrice": 35,
        "resalePrice": 15,
        "image": "villagre.jpg",
        "status": "available"
    },
    {
        "id": "villa-villanova-wildcats-nike-primary-logo-legend-performance-long-sleeve",
        "name": "Villanova Wildcats Nike Primary Logo Legend Performance Long Sleeve",
        "school": "Villa",
        "schoolDisplayName": "Villanova",
        "category": "long-sleeve",
        "size": "M",
        "condition": "Brand New",
        "brand": "Nike",
        "originalPrice": 45,
        "resalePrice": 25,
        "image": "villals.avif",
        "status": "available"
    },
    {
        "id": "villa-villanova-wildcats-nike-arch-tee",
        "name": "Villanova Wildcats Nike Arch Tee",
        "school": "Villa",
        "schoolDisplayName": "Villanova",
        "category": "tee",
        "size": "M",
        "condition": "Brand New",
        "brand": "Nike",
        "originalPrice": 40,
        "resalePrice": 20,
        "image": "villanikewild.avif",
        "status": "available"
    },
    {
        "id": "villa-villanova-wildcats-logo-comfort-tee",
        "name": "Villanova Wildcats Logo Comfort Tee",
        "school": "Villa",
        "schoolDisplayName": "Villanova",
        "category": "tee",
        "size": "M",
        "condition": "Brand New",
        "brand": "College apparel",
        "originalPrice": 40,
        "resalePrice": 20,
        "image": "villanavy.avif",
        "status": "available"
    },
    {
        "id": "villa-villanova-wildcats-graphic-tee",
        "name": "Villanova Wildcats Graphic Tee",
        "school": "Villa",
        "schoolDisplayName": "Villanova",
        "category": "tee",
        "size": "M",
        "condition": "Brand New",
        "brand": "College apparel",
        "originalPrice": 30,
        "resalePrice": 15,
        "image": "villaalt.png",
        "status": "available"
    },
    {
        "id": "bing-binghamton-university-champion-tee",
        "name": "Binghamton University Champion Tee",
        "school": "Bing",
        "schoolDisplayName": "Binghamton",
        "category": "tee",
        "size": "S",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 35,
        "resalePrice": 20,
        "image": "bingshirt.jpeg",
        "status": "available"
    },
    {
        "id": "dartmouth-dartmouth-college-under-armour-long-sleeve-tech",
        "name": "Dartmouth College Under Armour Long-Sleeve Tech",
        "school": "Dartmouth",
        "schoolDisplayName": "Dartmouth College",
        "category": "long-sleeve",
        "size": "L",
        "condition": "Brand New",
        "brand": "Under Armour",
        "originalPrice": 60,
        "resalePrice": 30,
        "image": "dartmouthls.jpg",
        "status": "available"
    },
    {
        "id": "dartmouth-dartmouth-college-nike-fly-2-0-shorts",
        "name": "Dartmouth College Nike Fly 2.0 Shorts",
        "school": "Dartmouth",
        "schoolDisplayName": "Dartmouth College",
        "category": "shorts",
        "size": "L",
        "condition": "Brand New",
        "brand": "Nike",
        "originalPrice": 60,
        "resalePrice": 25,
        "image": "dartmouthshorts.jpg",
        "status": "available"
    },
    {
        "id": "tulane-tulane-green-wave-champion-twill-crewneck",
        "name": "Tulane Green Wave Champion Twill Crewneck",
        "school": "Tulane",
        "schoolDisplayName": "Tulane",
        "category": "crewneck",
        "size": "S",
        "condition": "Brand New",
        "brand": "Champion",
        "originalPrice": 70,
        "resalePrice": 35,
        "image": "tulanepull.avif",
        "status": "available"
    },
    {
        "id": "delaware-university-of-delaware-champion-powerblend-hoodie",
        "name": "University of Delaware Champion Powerblend Hoodie",
        "school": "Delaware",
        "schoolDisplayName": "University of Delaware",
        "category": "hoodie",
        "size": "S",
        "condition": "Brand New",
        "brand": "Champion",
        "originalPrice": 55,
        "resalePrice": 25,
        "image": "udubhoodie.jpg",
        "status": "available"
    },
    {
        "id": "wisconsin-wisconsin-champion-bucky-badger-tee",
        "name": "Wisconsin Champion Bucky Badger Tee",
        "school": "Wisconsin",
        "schoolDisplayName": "University of Wisconsin",
        "category": "tee",
        "size": "M",
        "condition": "Brand New",
        "brand": "Champion",
        "originalPrice": 35,
        "resalePrice": 20,
        "image": "wiscotee.webp",
        "status": "available"
    },
    {
        "id": "upenn-university-of-pennsylvania-hoodie",
        "name": "University of Pennsylvania Hoodie",
        "school": "UPenn",
        "schoolDisplayName": "University of Pennsylvania",
        "category": "hoodie",
        "size": "S",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 75,
        "resalePrice": 35,
        "image": "upennhoodie.JPG",
        "status": "available"
    },
    {
        "id": "princeton-princeton-university-orange-champion-hoodie",
        "name": "Princeton University Orange Champion Hoodie",
        "school": "Princeton",
        "schoolDisplayName": "Princeton",
        "category": "hoodie",
        "size": "M",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 75,
        "resalePrice": 35,
        "image": "princetonhoodie.JPG",
        "status": "available"
    },
    {
        "id": "princeton-princeton-university-charcoal-champion-hoodie",
        "name": "Princeton University Charcoal Champion Hoodie",
        "school": "Princeton",
        "schoolDisplayName": "Princeton",
        "category": "hoodie",
        "size": "M",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 75,
        "resalePrice": 35,
        "image": "princetongrey.JPG",
        "status": "available"
    },
    {
        "id": "miamio-miami-university-vintage-90s-champion-hoodie",
        "name": "Miami University Vintage 90s Champion Hoodie",
        "school": "MiamiO",
        "schoolDisplayName": "Miami University (Ohio)",
        "category": "hoodie",
        "size": "M",
        "condition": "Like New",
        "brand": "Champion",
        "originalPrice": 65,
        "resalePrice": 30,
        "image": "product-images/miami-grey-hoodie.jpg",
        "status": "available"
    },
    {
        "id": "syracuse-syracuse-university-under-armour-orange-hoodie",
        "name": "Syracuse University Under Armour Orange Hoodie",
        "school": "Syracuse",
        "schoolDisplayName": "Syracuse",
        "category": "hoodie",
        "size": "M",
        "condition": "Like New",
        "brand": "Under Armour",
        "originalPrice": 70,
        "resalePrice": 30,
        "image": "syarcuseorangehoodie.jpg",
        "status": "available"
    },
    {
        "id": "unc-north-carolina-nike-vault-long-sleeve-tee",
        "name": "North Carolina Nike Vault Long Sleeve Tee",
        "school": "UNC",
        "schoolDisplayName": "North Carolina",
        "category": "long-sleeve",
        "size": "L",
        "condition": "Like New",
        "brand": "Nike",
        "originalPrice": 65,
        "resalePrice": 25,
        "image": "uncls.JPG",
        "status": "available"
    },
    {
        "id": "unc-north-carolina-tar-heels-retro-hoodie",
        "name": "North Carolina Tar Heels Retro Hoodie",
        "school": "UNC",
        "schoolDisplayName": "North Carolina",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "College apparel",
        "originalPrice": 75,
        "resalePrice": 35,
        "image": "unchoodie.JPG",
        "status": "available"
    },
    {
        "id": "unc-north-carolina-nike-tar-heels-hockey-hoodie",
        "name": "North Carolina Nike Tar Heels Hockey Hoodie",
        "school": "UNC",
        "schoolDisplayName": "North Carolina",
        "category": "hoodie",
        "size": "L",
        "condition": "Like New",
        "brand": "Nike",
        "originalPrice": 80,
        "resalePrice": 35,
        "image": "unchockey.JPG",
        "status": "available"
    }
];
